# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).

# Player.create(name: "", position: "", rating: , club: "", country: "", age: )

Player.create(name: "Lionel Messi", position: "FWD", rating: 93, club: "FC Barcelona", country: "Argentina", age: 33)
Player.create(name: "Cristiano Ronaldo", position: "FWD", rating: 92, club: "Juventus", country: "Portugal", age: 36)
Player.create(name: "Robert Lewandowski", position: "FWD", rating: 91, club: "Bayern Munich", country: "Poland", age: 32)
Player.create(name: "Neymar Jr", position: "FWD", rating: 91, club: "PSG", country: "Brazil", age: 29)
Player.create(name: "Jan Oblak", position: "GK", rating: 91, club: "Atletico Madrid", country: "Slovenia", age: 28)
Player.create(name: "Kylian Mbappe", position: "FWD", rating: 90, club: "PSG", country: "France", age: 22)
Player.create(name: "Marc-Andre ter Stegen", position: "GK", rating: 90, club: "FC Barcelona", country: "Germany", age: 28)
Player.create(name: "Sergio Ramos", position: "DEF", rating: 89, club: "Real Madrid", country: "Spain", age: 35)
Player.create(name: "Manuel Neuer", position: "GK", rating: 89, club: "Bayern Munich", country: "Germany", age: 35)
Player.create(name: "Karim Benzema", position: "FWD", rating: 89, club: "Real Madrid", country: "France", age: 33)
Player.create(name: "Casemiro", position: "MID", rating: 89, club: "Real Madrid", country: "Brazil", age: 29)
Player.create(name: "Thibaut Courtois", position: "GK", rating: 89, club: "Real Madrid", country: "Belgium", age: 28)
Player.create(name: "Harry Kane", position: "FWD", rating: 88, club: "Tottenham Hotspur", country: "England", age: 27)
Player.create(name: "Ngolo Kante", position: "MID", rating: 88, club: "Chelsea FC", country: "France", age: 30)
Player.create(name: "Joshua Kimmich", position: "MID", rating: 88, club: "Bayern Munich", country: "Germany", age: 26)
Player.create(name: "Toni Kroos", position: "MID", rating: 88, club: "Real Madrid", country: "Germany", age: 31)
Player.create(name: "Eden Hazard", position: "FWD", rating: 88, club: "Real Madrid", country: "Belgium", age: 30)
Player.create(name: "Paulo Dybala", position: "FWD", rating: 88, club: "Juventus", country: "Argentina", age: 27)
Player.create(name: "Luka Modric", position: "MID", rating: 88, club: "Real Madrid", country: "Croatia", age: 35)
Player.create(name: "Kalidou Koulibaly", position: "DEF", rating: 88, club: "Napoli SC", country: "Senegal", age: 29)
Player.create(name: "Son Heung-Min", position: "FWD", rating: 87, club: "Tottenham Hotspur", country: "South Korea", age: 28)
Player.create(name: "Erling Haaland", position: "FWD", rating: 84, club: "Borussia Dortmund", country: "Norway", age: 20)
Player.create(name: "Jadon Sancho", position: "MID", rating: 87, club: "Borussia Dortmund", country: "England", age: 21)
Player.create(name: "Marcus Rashford", position: "FWD", rating: 85, club: "Manchester United", country: "England", age: 23)
Player.create(name: "Romelu Lukaku", position: "FWD", rating: 85, club: "Inter Milan", country: "Belgium", age: 27)
Player.create(name: "Joao Felix", position: "FWD", rating: 81, club: "Atletico Madrid", country: "Portugal", age: 21)
Player.create(name: "Alphonso Davies", position: "DEF", rating: 81, club: "Bayern Munich", country: "Canada", age: 20)
Player.create(name: "Bruno Fernandes", position: "MID", rating: 87, club: "Manchester United", country: "Portugal", age: 26)
Player.create(name: "Frenkie de Jong", position: "MID", rating: 85, club: "FC Barcelona", country: "Netherlands", age: 23)
Player.create(name: "Lautaro Martinez", position: "FWD", rating: 84, club: "Inter Milan", country: "Argentina", age: 23)
Player.create(name: "Raphael Varane", position: "DEF", rating: 86, club: "Real Madrid", country: "France", age: 27)
Player.create(name: "Marcelo", position: "DEF", rating: 83, club: "Real Madrid", country: "Brazil", age: 32)


